### ISSUE TITLE
第三方App调用时，如果已经显示相同ViewController，还有必要push另一个吗？

### ISSUE THREAD

**Issue by calvingit** [douban/FRDIntent#10]
个人感觉这样好别扭，能不能先检测Top VC是否就是外部App需要显示的界面呢？如果是同样的VC，那只需要重新加载数据即可，不需要重新创建一个VC再push。

**Comment by guoshao-dev** [comment]
你说的有道理，但并不一定是绝对的。也可能有这样的需求：无论何种情况，都保留页面已有的数据。第三方调用本App时，即使本App恰好在第三方需要的页面上，在也不要刷新该页面的数据，而是推出一个新页面。

所以，如果你需要定制自己的转场，可以配置 FRDIntent 的 controllerDisplay。自己实现一个 FRDControllerDisplay 用于组装 FRDIntent 即可。
