### ISSUE TITLE
#探讨# TabBarViewController的几个Tab切换有必要用Intent吗？

### ISSUE THREAD

**Issue by calvingit** [douban/FRDIntent#12]
个人感觉TabBarViewController和它的几个子ViewController是强耦合的东西，把TabBarViewController当做一个整体来看比当做几个子模块看会更好。

还有一些比如ChildViewController的切换，似乎都限制在它的ParentController里面，这种解耦是没必要的。

不知道你怎么认为？

**Comment by guoshao-dev** [comment]
模块的划分有时候是根据业务的。如果，在业务上就是根据一个个 tab 划分的，那么，最好还是要切开。即使 TabBarViewController 这部分看起来有点不舒服。所以，这种划分都需要视情况而定。
