### ISSUE TITLE
startControllerForResult的display可以不限定为FRDPresentationDisplay吗？也有Push的情况

### ISSUE THREAD

**Issue by calvingit** [douban/FRDIntent#13]
比如下面这种，真正关心的是Done操作，对于用户Back并不关心。
如果限定死了FRDPresentationDisplay，定制一些动画也麻烦

![qq20161115-2](https://cloud.githubusercontent.com/assets/2109371/20299068/35b10ae0-ab54-11e6-9cc0-b0a683a14205.png)

**Comment by guoshao-dev** [comment]
startControllerForResult 也需要传入一个FRDIntent。你可以定义自己的 FRDControllerDisplay，赋给 FRDIntent，就可以定制进入动画了。返回动画也是相同的道理。

**Comment by calvingit** [comment]
可是你已经写死了，没有去获取intent的display

**Comment by guoshao-dev** [comment]
多谢，我看了一下代码，这一段确实写死了。

回头改为：如果 intent 有 自己的 controllerDisplay，就使用自己的 controllerDisplay。这样是否可以解决你的问题？

**Comment by calvingit** [comment]
可以
