### ISSUE TITLE
`FRDIntentForResultSendable`协议的方法`onControllerResult`的 `data`参数直接弄成字典好了？

### ISSUE THREAD

**Issue by calvingit** [douban/FRDIntent#16]
目前`data`是`FRDIntent`类型，但我觉得没必要，改成 `[String: AnyObject]` 就可以了，因为intent的URL等属性又没有用到，最多extra就包含返回结果了。
PR：#17

**Comment by guoshao-dev** [comment]
https://github.com/douban/FRDIntent/pull/43
