### ISSUE TITLE
FRDIntent 跳转到VC后，在pop，这个VC不释放啊

### ISSUE THREAD

**Issue by FengDeng** [douban/FRDIntent#18]
FRDIntent *intent = [[FRDIntent alloc] initWithPathIdentifier:@"/video_detail"];
        [intent putExtraWithName:@"videoId" data: [NSString stringWithFormat:@"%ld",(long)self.videoList[indexPath.row].videoId]];
        [self startControllerWithIntent: intent];

**Comment by calvingit** [comment]
@lincode 确实有这问题，已经pop出Navigation的栈了，但是没有释放掉，我没看出哪里的问题，你再看看？

**Comment by guoshao-dev** [comment]
我也试了以下，确实没有调用到 dealloc。我花了一段时间查看了一下代码，但还没有发现哪儿写错了，导致了这个问题。我再看看吧，有结果告知大家。

**Comment by guoshao-dev** [comment]
@FengDeng @calvingit https://github.com/douban/FRDIntent/pull/20

**Comment by guoshao-dev** [comment]
fixed
