### ISSUE TITLE
从外部进APP 使用URLRoutes 

### ISSUE THREAD

**Issue by YuanzhengWang** [douban/FRDIntent#24]
从外部进APP 使用URLRoutes  切换模式是present方式 然后无法实现dismiss方法

**Comment by bigyelow** [comment]
能描述清楚些吗？route 的时候看起来只需要提供 display 方式，为什么需要 dismiss ？

**Comment by guoshao-dev** [comment]
@YuanzhengWang Demo 中的例子运行良好。Safari 中输入 `frdintent://frdintent.com/user/123/story/123` 可以以 present 方式 进入 ThirdViewController，并且可以正常 dismiss。

**Comment by YuanzhengWang** [comment]
知道原因了 sorry
