### ISSUE TITLE
如何对URL进行参数校验？

### ISSUE THREAD

**Issue by YuanzhengWang** [douban/FRDIntent#25]
RT ： 需要URL进行参数的比对跟校验才确定是否跳转或者跳转H5的处理

**Comment by YuanzhengWang** [comment]
标题写错了是如何

**Comment by guoshao-dev** [comment]
还无法在接收方进行 url 参数校验。近期正在思考如何加入这个功能。

**Comment by YuanzhengWang** [comment]
如果参数不校验的话 没有真正程度上的解耦了

**Comment by bigyelow** [comment]
@lincode @YuanzhengWang 这里的参数校验说的是在 `startController()` 的时候校验 `extractParameters()` 方法返回的 `parameters` 吗？

**Comment by guoshao-dev** [comment]
这个 pr 应该满足了这个需求：https://github.com/douban/FRDIntent/pull/30 在 demo 的 FourthViewController 演示了如何使用。@YuanzhengWang
