### ISSUE TITLE
为什么我 pod install 下来的文件不完整？

### ISSUE THREAD

**Issue by Humein** [douban/FRDIntent#34]
pod 'FRDIntent/Intent', :git => 'https://github.com/douban/FRDIntent.git', :commit => '0.9.0'

![image](https://cloud.githubusercontent.com/assets/12099831/23207919/035c31e6-f92e-11e6-9bbd-a60ae1d8566b.png)

**Comment by Humein** [comment]
pod 'FRDIntent', :git => 'https://github.com/douban/FRDIntent.git', :commit => '0.8.0' 这个也是不行的

**Comment by guoshao-dev** [comment]
用最新版试试，应该是还没来得及打版本。

pod 'FRDIntent', :git => 'https://github.com/douban/FRDIntent.git', :commit => '2bd59bd'

**Comment by Humein** [comment]
![image](https://cloud.githubusercontent.com/assets/12099831/23240023/c9a70336-f9a5-11e6-9550-02fc8bf0a88e.png)
呃 貌似 还不可以-。-

**Comment by bigyelow** [comment]
先执行 pod repo update

**Comment by Humein** [comment]
我的还是不行 你的可以吗？

**Comment by bigyelow** [comment]
可以啊，执行了 pod repo update 了吗？执行了有报错吗？
 去 ~/.coocpoda/repos/master 里看看 FRDIntent 为什么没有这个 commit。

**Comment by guoshao-dev** [comment]
@QinKingHan  试试下面

```
pod 'FRDIntent', :git => 'https://github.com/douban/FRDIntent.git', :commit => 'ea5d483' 
```

```
pod repo update
pod update
```
