### ISSUE TITLE
Tries Tree 搜索 placeholder 时存在 bug

### ISSUE THREAD

**Issue by guoshao-dev** [douban/FRDIntent#48]
Tries的实现，搜索placeholder时还是有 bug

注册 /a/:b/c/
注册 /a/x/c/d/

route /a/x/c/ 不能跳转到/a/:b/c/

**Comment by hao-feng** [comment]
再来一个
注册 /a/b/c/e
注册 /a/b/

route /a/b/c 应该返回/a/b的值，实际返回了c的值，为空

**Comment by guoshao-dev** [comment]
😢

**Comment by guoshao-dev** [comment]
第二个 bug 改好了。第一个有点不想 fix 了。会使情况变得很复杂。

**Comment by guoshao-dev** [comment]
要不你提一个 PR 试试，看能否简单点完成。

**Comment by hao-feng** [comment]
第一个情况确实比较麻烦

**Comment by hao-feng** [comment]
我不确定有优雅的解决方案

**Comment by hao-feng** [comment]
fixed https://github.com/douban/FRDIntent/pull/50
