### ISSUE TITLE
通过 plist 注册不成功

### ISSUE THREAD

**Issue by hydyy** [douban/FRDIntent#57]
![image](https://user-images.githubusercontent.com/1254987/33239597-29d8e954-d2e0-11e7-953c-c1e9045dfbe1.png)

通过 plist 注册不成功，但是单独注册没问题，我看到里面的判断始终过不去，不懂为什么

if let clazz = NSClassFromString(className) as? FRDIntentReceivable.Type 
这里的判断过不去，我的 TestController

![image](https://user-images.githubusercontent.com/1254987/33239605-5d83f73a-d2e0-11e7-951e-c972f6157590.png)

**Comment by hydyy** [comment]
![image](https://user-images.githubusercontent.com/1254987/33239672-b552357a-d2e1-11e7-8d97-ae7321c21441.png)

我的注册文件里加上 AppName. 就 Ok 了，可是感觉不太好啊，能否内部处理一下？

**Comment by hao-feng** [comment]
@hydyy 在你的这个问题中，className前是需要加上AppName。很遗憾，我们并不能把这个放入FRDIntent，因为在swift中，swift class前缀是会有包名的。比如，在你的项目中引入了A的pod, pod中有class B, 那么B的真实名字就会为A.B

**Comment by hydyy** [comment]
没问题，但是应该在文档使用上说明一下的
