### ISSUE TITLE
有计划支持Storyboard？

### ISSUE THREAD

**Issue by wyhazq** [douban/FRDIntent#8]
如题

**Comment by guoshao-dev** [comment]
你是说由一个页面跳转到 Storyboard 中画好的一个 UIViewController 吗？

我理解中 Storyboard 自身就可以完成所有页面的调整关系的规划。并且没有代码级别的耦合，因为调整关系都在 Storyboard 中了，本质上是使用 xml 来注册页面调整关系。如果，同时还使用 FRDIntent 折衷代码方式管理调整。那就意味着一个 App 中有两套页面调用管理系统。这似乎并不是一个好的选择。

一般一个需要解耦 view controller 的项目都是较大的项目了。在一个较大的项目中使用 Storyboad 有不少局限，并不是一个好选择。如果基于和设计师合作，需要一些图形化页面设计工具。那么使用 xib 实现会是一个不错的折衷方案。xib 实现的衙门完全可以使用 FRDIntent 完成调用。

所以，现阶段，直觉的答案是不会支持 Storyboard。

**Comment by wyhazq** [comment]
某些小的模块，Storyboard能节省很多时间，假如B模块是使用Storyboard的，A模块的某个页面跳转到B模块的某个页面需要传值的话，就必须引入B模块了，苦于无法解决这个问题。不过FRDIntent能够解决大部分的问题了，感谢！
